/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export declare namespace DeltTrader {
  export type ListingStruct = { contractAddr: string; id: BigNumberish };

  export type ListingStructOutput = [string, BigNumber] & {
    contractAddr: string;
    id: BigNumber;
  };

  export type BidStruct = { bidder: string; bid: BigNumberish };

  export type BidStructOutput = [string, BigNumber] & {
    bidder: string;
    bid: BigNumber;
  };

  export type TransactionStruct = {
    buyer: string;
    seller: string;
    price: BigNumberish;
    amount: BigNumberish;
    auctioned: boolean;
    completed: boolean;
  };

  export type TransactionStructOutput = [
    string,
    string,
    BigNumber,
    BigNumber,
    boolean,
    boolean
  ] & {
    buyer: string;
    seller: string;
    price: BigNumber;
    amount: BigNumber;
    auctioned: boolean;
    completed: boolean;
  };
}

export interface DeltTraderInterface extends utils.Interface {
  functions: {
    "activeAuctions(address,uint256)": FunctionFragment;
    "addListing((address,uint256),uint256,uint256,bool)": FunctionFragment;
    "auctions(address,uint256)": FunctionFragment;
    "balances(address)": FunctionFragment;
    "bid((address,uint256))": FunctionFragment;
    "endAuction((address,uint256))": FunctionFragment;
    "erc721(address)": FunctionFragment;
    "getListings((address,uint256))": FunctionFragment;
    "purchace((address,uint256))": FunctionFragment;
    "removeListing((address,uint256))": FunctionFragment;
    "setContractStandard(address,bool)": FunctionFragment;
    "transactions(address,uint256,uint256)": FunctionFragment;
    "withdraw(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "activeAuctions"
      | "addListing"
      | "auctions"
      | "balances"
      | "bid"
      | "endAuction"
      | "erc721"
      | "getListings"
      | "purchace"
      | "removeListing"
      | "setContractStandard"
      | "transactions"
      | "withdraw"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "activeAuctions",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addListing",
    values: [DeltTrader.ListingStruct, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "auctions",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "balances", values: [string]): string;
  encodeFunctionData(
    functionFragment: "bid",
    values: [DeltTrader.ListingStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "endAuction",
    values: [DeltTrader.ListingStruct]
  ): string;
  encodeFunctionData(functionFragment: "erc721", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getListings",
    values: [DeltTrader.ListingStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "purchace",
    values: [DeltTrader.ListingStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "removeListing",
    values: [DeltTrader.ListingStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setContractStandard",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transactions",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "activeAuctions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addListing", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "auctions", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balances", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "endAuction", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "erc721", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getListings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "purchace", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setContractStandard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transactions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "AuctionEnd(tuple,address,uint256,uint256)": EventFragment;
    "AuctionStart(tuple,uint256,uint256)": EventFragment;
    "BidPlaced(tuple,tuple[])": EventFragment;
    "Purchaced(tuple,address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AuctionEnd"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AuctionStart"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BidPlaced"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Purchaced"): EventFragment;
}

export interface AuctionEndEventObject {
  _listing: DeltTrader.ListingStructOutput;
  highestBidder: string;
  highestBid: BigNumber;
  amount: BigNumber;
}
export type AuctionEndEvent = TypedEvent<
  [DeltTrader.ListingStructOutput, string, BigNumber, BigNumber],
  AuctionEndEventObject
>;

export type AuctionEndEventFilter = TypedEventFilter<AuctionEndEvent>;

export interface AuctionStartEventObject {
  _listing: DeltTrader.ListingStructOutput;
  price: BigNumber;
  endAt: BigNumber;
}
export type AuctionStartEvent = TypedEvent<
  [DeltTrader.ListingStructOutput, BigNumber, BigNumber],
  AuctionStartEventObject
>;

export type AuctionStartEventFilter = TypedEventFilter<AuctionStartEvent>;

export interface BidPlacedEventObject {
  _listing: DeltTrader.ListingStructOutput;
  updatedBids: DeltTrader.BidStructOutput[];
}
export type BidPlacedEvent = TypedEvent<
  [DeltTrader.ListingStructOutput, DeltTrader.BidStructOutput[]],
  BidPlacedEventObject
>;

export type BidPlacedEventFilter = TypedEventFilter<BidPlacedEvent>;

export interface PurchacedEventObject {
  _listing: DeltTrader.ListingStructOutput;
  buyer: string;
  price: BigNumber;
  amount: BigNumber;
}
export type PurchacedEvent = TypedEvent<
  [DeltTrader.ListingStructOutput, string, BigNumber, BigNumber],
  PurchacedEventObject
>;

export type PurchacedEventFilter = TypedEventFilter<PurchacedEvent>;

export interface DeltTrader extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DeltTraderInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    activeAuctions(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    addListing(
      _listing: DeltTrader.ListingStruct,
      _price: BigNumberish,
      _amount: BigNumberish,
      _auction: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    auctions(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        seller: string;
        endAt: BigNumber;
        initPrice: BigNumber;
      }
    >;

    balances(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    bid(
      _listing: DeltTrader.ListingStruct,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    endAuction(
      _listing: DeltTrader.ListingStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    erc721(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    getListings(
      _listing: DeltTrader.ListingStruct,
      overrides?: CallOverrides
    ): Promise<[DeltTrader.TransactionStructOutput[]]>;

    purchace(
      _listing: DeltTrader.ListingStruct,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    removeListing(
      _listing: DeltTrader.ListingStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setContractStandard(
      _contractAddr: string,
      _isErc721: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transactions(
      arg0: string,
      arg1: BigNumberish,
      arg2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, BigNumber, boolean, boolean] & {
        buyer: string;
        seller: string;
        price: BigNumber;
        amount: BigNumber;
        auctioned: boolean;
        completed: boolean;
      }
    >;

    withdraw(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  activeAuctions(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  addListing(
    _listing: DeltTrader.ListingStruct,
    _price: BigNumberish,
    _amount: BigNumberish,
    _auction: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  auctions(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber] & {
      seller: string;
      endAt: BigNumber;
      initPrice: BigNumber;
    }
  >;

  balances(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  bid(
    _listing: DeltTrader.ListingStruct,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  endAuction(
    _listing: DeltTrader.ListingStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  erc721(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  getListings(
    _listing: DeltTrader.ListingStruct,
    overrides?: CallOverrides
  ): Promise<DeltTrader.TransactionStructOutput[]>;

  purchace(
    _listing: DeltTrader.ListingStruct,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  removeListing(
    _listing: DeltTrader.ListingStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setContractStandard(
    _contractAddr: string,
    _isErc721: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transactions(
    arg0: string,
    arg1: BigNumberish,
    arg2: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, string, BigNumber, BigNumber, boolean, boolean] & {
      buyer: string;
      seller: string;
      price: BigNumber;
      amount: BigNumber;
      auctioned: boolean;
      completed: boolean;
    }
  >;

  withdraw(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    activeAuctions(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    addListing(
      _listing: DeltTrader.ListingStruct,
      _price: BigNumberish,
      _amount: BigNumberish,
      _auction: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    auctions(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        seller: string;
        endAt: BigNumber;
        initPrice: BigNumber;
      }
    >;

    balances(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    bid(
      _listing: DeltTrader.ListingStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    endAuction(
      _listing: DeltTrader.ListingStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    erc721(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    getListings(
      _listing: DeltTrader.ListingStruct,
      overrides?: CallOverrides
    ): Promise<DeltTrader.TransactionStructOutput[]>;

    purchace(
      _listing: DeltTrader.ListingStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    removeListing(
      _listing: DeltTrader.ListingStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    setContractStandard(
      _contractAddr: string,
      _isErc721: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    transactions(
      arg0: string,
      arg1: BigNumberish,
      arg2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, BigNumber, boolean, boolean] & {
        buyer: string;
        seller: string;
        price: BigNumber;
        amount: BigNumber;
        auctioned: boolean;
        completed: boolean;
      }
    >;

    withdraw(amount: BigNumberish, overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "AuctionEnd(tuple,address,uint256,uint256)"(
      _listing?: null,
      highestBidder?: null,
      highestBid?: null,
      amount?: null
    ): AuctionEndEventFilter;
    AuctionEnd(
      _listing?: null,
      highestBidder?: null,
      highestBid?: null,
      amount?: null
    ): AuctionEndEventFilter;

    "AuctionStart(tuple,uint256,uint256)"(
      _listing?: null,
      price?: null,
      endAt?: null
    ): AuctionStartEventFilter;
    AuctionStart(
      _listing?: null,
      price?: null,
      endAt?: null
    ): AuctionStartEventFilter;

    "BidPlaced(tuple,tuple[])"(
      _listing?: null,
      updatedBids?: null
    ): BidPlacedEventFilter;
    BidPlaced(_listing?: null, updatedBids?: null): BidPlacedEventFilter;

    "Purchaced(tuple,address,uint256,uint256)"(
      _listing?: null,
      buyer?: null,
      price?: null,
      amount?: null
    ): PurchacedEventFilter;
    Purchaced(
      _listing?: null,
      buyer?: null,
      price?: null,
      amount?: null
    ): PurchacedEventFilter;
  };

  estimateGas: {
    activeAuctions(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    addListing(
      _listing: DeltTrader.ListingStruct,
      _price: BigNumberish,
      _amount: BigNumberish,
      _auction: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    auctions(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    balances(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    bid(
      _listing: DeltTrader.ListingStruct,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    endAuction(
      _listing: DeltTrader.ListingStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    erc721(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    getListings(
      _listing: DeltTrader.ListingStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    purchace(
      _listing: DeltTrader.ListingStruct,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    removeListing(
      _listing: DeltTrader.ListingStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setContractStandard(
      _contractAddr: string,
      _isErc721: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transactions(
      arg0: string,
      arg1: BigNumberish,
      arg2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdraw(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    activeAuctions(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addListing(
      _listing: DeltTrader.ListingStruct,
      _price: BigNumberish,
      _amount: BigNumberish,
      _auction: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    auctions(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    balances(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bid(
      _listing: DeltTrader.ListingStruct,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    endAuction(
      _listing: DeltTrader.ListingStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    erc721(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getListings(
      _listing: DeltTrader.ListingStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    purchace(
      _listing: DeltTrader.ListingStruct,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    removeListing(
      _listing: DeltTrader.ListingStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setContractStandard(
      _contractAddr: string,
      _isErc721: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transactions(
      arg0: string,
      arg1: BigNumberish,
      arg2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdraw(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
