/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DeltAttributes } from "./DeltAttributes";
export type { DeltItems } from "./DeltItems";
export type { DeltTrader } from "./DeltTrader";
