/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as deltSol from "./delt.sol";
export type { deltSol };
export type { DeltItems } from "./DeltItems";
