/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as draftErc721VotesUpgradeableSol from "./draft-ERC721VotesUpgradeable.sol";
export type { draftErc721VotesUpgradeableSol };
export type { ERC721BurnableUpgradeable } from "./ERC721BurnableUpgradeable";
export type { ERC721EnumerableUpgradeable } from "./ERC721EnumerableUpgradeable";
export type { ERC721URIStorageUpgradeable } from "./ERC721URIStorageUpgradeable";
export type { IERC721EnumerableUpgradeable } from "./IERC721EnumerableUpgradeable";
export type { IERC721MetadataUpgradeable } from "./IERC721MetadataUpgradeable";
